defaults: &defaults
  app_domain: localhost:3000
  
  site_title: Invoices
  
  default_locale: :en

# -----------------------------------------------------------------------------------

development:
  <<: *defaults
  domain: localhost:3000

test:
  <<: *defaults
  domain: test.host

production:
  <<: *defaults
  domain: localhost:3000
